FROM python:3.11-slim

WORKDIR /app

COPY requirements-train.txt .
RUN pip install --no-cache-dir -r requirements-train.txt

COPY scripts ./scripts
COPY churnguard ./churnguard

ENV PYTHONPATH=/app

CMD ["python", "-u", "scripts/register_model.py"]